### ISSUE TITLE
爬虫出错了

### ISSUE THREAD

**Issue by nullmz** [T0217/bilibili_sentiment_analysis#1]
提示错误号412，由于触发bilinili安全风控策略，访问请求被拒绝

**Comment by T0217** [comment]
> 提示错误号412，由于触发bilinili安全风控策略，访问请求被拒绝

尝试加cookie和headers，并刷新界面

**Comment by T0217** [comment]
> > 提示错误号412，由于触发bilinili安全风控策略，访问请求被拒绝
> 
> 尝试加cookie和headers，并刷新界面

已修改。
